### ISSUE TITLE
RECORD member types must be declared in source before the record is declared.

### ISSUE THREAD

**Issue by gitlarryf** [ghewgill/neon-lang#107]
When a RECORD type is declared in source, any members it declares that are not of intrinsic types will cause an N3011 compile error if they are not declared above the containing record.

The following code demonstrates this issue:

TYPE foo IS RECORD
    Member: Bar
END RECORD

TYPE Bar IS RECORD
    Data: String
END RECORD

**Comment by ghewgill** [comment]
This is by design. Types must be declared before they are used, to avoid problems with recursively contained types (A contains B contains A ...). The exception is you can forward declare a *pointer* to a type.
