### ISSUE TITLE
tmp folder is being left with files in it after a build

### ISSUE THREAD

**Issue by gitlarryf** [ghewgill/neon-lang#122]
SConstruct is leaving files in the .\tmp folder, making it very difficult to run tests that create files, or copy files that already exist.  If the tests are ran IN ORDER, it is easy to ensure certain behavior, but I don't think we should rely on the ORDER of the tests.

**Comment by ghewgill** [comment]
I don't think the contents of the tmp folder should be relevant for the tests. Each individual test should make sure that it can run no matter what the contents of the tmp directory are. Then it doesn't matter what order the tests run in.

**Comment by gitlarryf** [comment]
I don't agree.  Take for example this piece of sample code I created in the `file.neon` library for the function `file.copy()`, ok?

'
...
 |  Example:
 | > IMPORT file
 | >
 | > TRY
 | >     file.copy("./LICENSE.txt", "/tmp/LICENSE1.txt")
 | > EXCEPTION FileExistsException DO
 | >     print("File copy failed.  Destination file already exists.")
 | > END TRY
...
`
Now.  The problem is, the first time Neon is built with SCons, it will build perfectly.  But, there will now be a /tmp/LICENSE1.txt file that exists in the temp directory.  So, a SECOND run of SCons will throw the exception, and print the error.  Now, this isn't a HUGE deal as far as the documentation docs go, because they aren't checked and validated against their results like the tests in our t/ folder.  So, imagine this same piece of code in a sample under t/.  Now, you get different results when running the same test...  THIS is why I think it should be cleaned out at the start of the SCons run.

**Comment by ghewgill** [comment]
Your test is incomplete in this case. If your `file.copy()` call expects that the destination file does not exist, then the test must first ensure that the file does not exist (by deleting it, if necessary).

It is a general principle of test design that tests should be runnable, repeatedly, in isolation. They should not depend on something else cleaning up a test environment first.

**Comment by gitlarryf** [comment]
Ok, I can't really disagree with that, except that I'm attempting to make the tests run in isolation, and calling file.delete() BEFORE file.copy() runs our tests "out of order", just due to the natural (general) alphabetical ordering...  I will tweak the tests to make sure that they DO run properly, in this case...
