### ISSUE TITLE
Multiline Assertions crash the analyzer

### ISSUE THREAD

**Issue by gitlarryf** [ghewgill/neon-lang#160]
The follow code crashes the Neon executer:

```
LET n: Number := 5

ASSERT
(n - 2*(n+1)) = 0
```

**Comment by ghewgill** [comment]
This is not an executor crash, it crashes in the analyzer. Updated description.

The reason is the code that attempts to extract fragments of the assertion expression does not currently account for the expression possibly being spread over more than one line.
