### ISSUE TITLE
Add SQLite Switch to the SConstruct build file.

### ISSUE THREAD

**Issue by gitlarryf** [ghewgill/neon-lang#171]
A switch needs to be added to the SConstruct file that enables/disables the Embedded SQL support in Neon.  If the programmer attempts to use embedded SQL, and the compiler does not support it, an error should be thrown.  The same should hold true for the executor, just in case a neonx attempts to execute a .neonx file that WAS compiled with Embedded SQL.

The default value should of course be TRUE, and it might be just wize to only accept this switch if MINIMAL=1, but I'm not dead set on that, and it might be useful to be able to compile a full neonx, just WITHOUT Embedded SQL.

**Comment by ghewgill** [comment]
I don't want to add a switch for something like this without a good reason. The SQLite module is highly portable and should build on just about anything. Certainly it will build if the rest of the system builds (C++11).

If we were to add a switch like this, there would need to be strong justification for it.
