### ISSUE TITLE
Assigning to the LAST array element throws compiler error N3058.

### ISSUE THREAD

**Issue by gitlarryf** [ghewgill/neon-lang#172]
The following code results in a compiler error: N3058 "expression is not assignable".

     VAR arr: Array<String> := []
     arr[LAST] := "Test"

However, the following code works:

     VAR arr: Array<String> := []
     arr[LAST TO LAST] := ["Test"]

The code above also crashes the REPL.

**Comment by ghewgill** [comment]
Duplicate of #163.
