### ISSUE TITLE
Code comments do not mix with embedded SQL

### ISSUE THREAD

**Issue by gitlarryf** [ghewgill/neon-lang#293]
The following code demonstrates how Neon comments are not allowed in multi-line SQL statements.

```
EXEC SQL CONNECT TO "mydb.db";  # Works...
EXEC SQL DROP TABLE IF EXISTS role_type;  # Works...
EXEC SQL CREATE TABLE role_type(
     role_type_id   INTEGER PRIMARY KEY NOT NULL, # Does not work...
     role_type_desc STRING  #| Nor does this. |#
);
```
If used, an exception is raised, because `#` is an invalid char.

**Comment by ghewgill** [comment]
Everything between `EXEC SQL` and the ending `;` is passed verbatim to SQLite. Therefore, in order to include comments in embedded SQL, one must use [SQLite comments](https://www.sqlite.org/lang_comment.html):

    EXEC SQL CREATE TABLE role_type(
         role_type_id   INTEGER PRIMARY KEY NOT NULL, -- Commenting this line
         role_type_desc STRING  -- and this line too.
    );

**Comment by gitlarryf** [comment]
Nice!  Ok.  Got it.  Thank you for clarifying that.
