### ISSUE TITLE
json.encode() encodes an empty Dictionary as an empty Array, when an Object is used in a RECORD.

### ISSUE THREAD

**Issue by gitlarryf** [ghewgill/neon-lang#405]
The following code
```
IMPORT json

TYPE Req IS RECORD
     Data: Object
END RECORD

print(json.encode(Req(Data WITH {})))
```
Outputs: `{"Data":[]}` which is incorrect.

Changing Data from an `Object` to a `Dictionary<String>` does output the correct string:
`{"Data":{}}`

**Comment by ghewgill** [comment]
There is a shorter example that demonstrates the problem, without bringing in the json library:

    > print({})
    []

The output should be `{}`.
