### ISSUE TITLE
Neon doesn't handle nested comments well

### ISSUE THREAD

**Issue by gitlarryf** [ghewgill/neon-lang#456]
The following code is not being handled as it should.
`/* /* Comment Test */ */`
This will produce an N2033 error, proving that the first closing comment token closes the first, rather than nesting the comments.  I feel that the lexer should count opening and closing comment tokens and match them up.  This entire line should be handled as a single comment.

**Comment by ghewgill** [comment]
Block comments may not nest. https://neon-lang.dev/docs/neon-lang/0.1/reference/lexical.html#_comments
